@startuml
[AdminPage]
note top of AdminPage
Roles:
- changing passwd and username
- changing time of update from sensors (info that it will be updated on new pairing)
- setting sensor names (only for paired sensors transmitted by host)
end note

package "Host" {
[EspNow]
[WebView]
[EspNow]
[ConfStorage] as ConfStorage
[WebView]..>[AdminPage]: On load: sensors MACs and Names
}

@enduml